export const wordPairs = [
  ['Apple', 'Pear'],
  ['Dog', 'Cat'],
  ['Sun', 'Moon'],
  ['Car', 'Bike'],
  ['Pizza', 'Pasta'],
  ['Coffee', 'Tea'],
  ['Chair', 'Table'],
  ['Book', 'Magazine'],
  ['Tree', 'Bush'],
  ['Beach', 'Desert'],
  ['Mountain', 'Hill'],
  ['River', 'Stream'],
  ['Ocean', 'Sea'],
  ['Fire', 'Flame'],
  ['Bread', 'Toast'],
  ['Phone', 'Tablet'],
  ['Window', 'Door'],
  ['Laptop', 'Desktop'],
  ['Shoe', 'Boot'],
  ['Hat', 'Cap'],
  ['Pen', 'Pencil'],
  ['Fork', 'Spoon'],
  ['Knife', 'Blade'],
  ['Cup', 'Mug'],
  ['Watch', 'Clock'],
  ['Suit', 'Tuxedo'],
  ['Tie', 'Bowtie'],
  ['Milk', 'Juice'],
  ['Water', 'Soda'],
  ['Wine', 'Beer'],
  ['Guitar', 'Violin'],
  ['Piano', 'Keyboard'],
  ['Drum', 'Cymbal'],
  ['Plane', 'Helicopter'],
  ['Bus', 'Train'],
  ['Truck', 'Van'],
  ['Boat', 'Ship'],
  ['Fish', 'Shrimp'],
  ['Elephant', 'Rhino'],
  ['Lion', 'Tiger'],
  ['Butterfly', 'Bee'],
  ['Spider', 'Ant'],
  ['Glass', 'Bottle'],
  ['Mirror', 'Window'],
  ['Light', 'Lamp'],
  ['Candle', 'Torch'],
  ['Belt', 'Strap'],
  ['Jacket', 'Coat'],
  ['Pillow', 'Cushion'],
  ['Blanket', 'Quilt'],
  ['Sofa', 'Couch'],
  ['Curtain', 'Blinds'],
  ['Shirt', 'Blouse'],
  ['Shorts', 'Pants'],
  ['Sock', 'Glove'],
  ['Ring', 'Bracelet'],
  ['Necklace', 'Earring'],
  ['Scarf', 'Shawl'],
  ['Wallet', 'Purse'],
  ['Bag', 'Backpack'],
  ['Shoelace', 'Ribbon'],
  ['Cabbage', 'Lettuce'],
  ['Carrot', 'Radish'],
  ['Pepper', 'Chili'],
  ['Onion', 'Garlic'],
  ['Tomato', 'Cucumber'],
  ['Potato', 'Sweet Potato'],
  ['Peach', 'Plum'],
  ['Strawberry', 'Raspberry'],
  ['Blueberry', 'Blackberry'],
  ['Banana', 'Plantain'],
  ['Grape', 'Cherry'],
  ['Orange', 'Lemon'],
  ['Lime', 'Grapefruit'],
  ['Melon', 'Watermelon'],
  ['Pineapple', 'Mango'],
  ['Coconut', 'Papaya'],
  ['Kiwi', 'Guava'],
  ['Bamboo', 'Cane'],
  ['Maple', 'Oak'],
  ['Rose', 'Tulip'],
  ['Lily', 'Daisy'],
  ['Iris', 'Orchid'],
  ['Carnation', 'Chrysanthemum'],
  ['Sunflower', 'Marigold'],
  ['Lavender', 'Mint'],
  ['Basil', 'Oregano'],
  ['Parsley', 'Cilantro'],
  ['Thyme', 'Rosemary'],
  ['Cinnamon', 'Nutmeg'],
  ['Ginger', 'Turmeric'],
  ['Sugar', 'Salt'],
  ['Pepper', 'Paprika'],
  ['Rice', 'Quinoa'],
  ['Wheat', 'Barley'],
  ['Corn', 'Maize'],
  ['Oats', 'Rye'],
  ['Bread', 'Bagel'],
  ['Biscuit', 'Cookie'],
  ['Cake', 'Pie'],

    // Food
  ['Burger', 'Sandwich'],
  ['Spaghetti', 'Noodles'],
  ['Chocolate', 'Candy'],
  ['Ice Cream', 'Gelato'],
  ['Coffee', 'Tea'],
  ['Rice', 'Quinoa'],
  ['Salad', 'Soup'],
  ['Pancake', 'Waffle'],
  ['Bread', 'Bagel'],
  ['Sushi', 'Sashimi'],
  ['Taco', 'Burrito'],
  ['Donut', 'Croissant'],
  ['Steak', 'Ribs'],
  ['Hotdog', 'Sausage'],
  ['Cheese', 'Butter'],
  ['Yogurt', 'Pudding'],
  ['Muffin', 'Cupcake'],
  // Cities
  ['New York', 'Los Angeles'],
  ['Paris', 'London'],
  ['Tokyo', 'Kyoto'],
  ['Berlin', 'Munich'],
  ['Sydney', 'Melbourne'],
  ['Beijing', 'Shanghai'],
  ['Mumbai', 'Delhi'],
  ['Rome', 'Venice'],
  ['San Francisco', 'Seattle'],
  ['Toronto', 'Vancouver'],
  ['Chicago', 'Houston'],
  ['Barcelona', 'Madrid'],
  ['Bangkok', 'Phuket'],
  ['Istanbul', 'Ankara'],
  ['Dubai', 'Abu Dhabi'],
  ['Cape Town', 'Johannesburg'],
  ['Moscow', 'Saint Petersburg'],
  ['Buenos Aires', 'Santiago'],
  ['Rio de Janeiro', 'São Paulo'],
  ['Athens', 'Thessaloniki'],
  // Countries
  ['USA', 'Canada'],
  ['China', 'Japan'],
  ['Germany', 'France'],
  ['Brazil', 'Argentina'],
  ['Italy', 'Spain'],
  ['Australia', 'New Zealand'],
  ['Russia', 'Ukraine'],
  ['India', 'Pakistan'],
  ['Mexico', 'Cuba'],
  ['South Korea', 'North Korea'],
  ['England', 'Scotland'],
  ['Sweden', 'Norway'],
  ['Egypt', 'Morocco'],
  ['South Africa', 'Nigeria'],
  ['Turkey', 'Greece'],
  ['Israel', 'Palestine'],
  ['Thailand', 'Vietnam'],
  ['Saudi Arabia', 'Iran'],
  ['Philippines', 'Indonesia'],
  ['Malaysia', 'Singapore'],
  // Animals
  ['Lion', 'Tiger'],
  ['Elephant', 'Rhino'],
  ['Horse', 'Donkey'],
  ['Eagle', 'Falcon'],
  ['Shark', 'Whale'],
  ['Penguin', 'Seal'],
  ['Kangaroo', 'Wallaby'],
  ['Panda', 'Koala'],
  ['Snake', 'Lizard'],
  ['Wolf', 'Fox'],
  ['Rabbit', 'Hare'],
  ['Parrot', 'Crow'],
  ['Bee', 'Wasp'],
  ['Butterfly', 'Moth'],
  ['Turtle', 'Tortoise'],
  ['Frog', 'Toad'],
  ['Owl', 'Hawk'],
  ['Dolphin', 'Porpoise'],
  ['Goat', 'Sheep'],
  ['Buffalo', 'Bison'],
  ['Reddit', 'Tumblr'],
  ['Spotify', 'SoundCloud'],
  ['Wikipedia', 'Britannica'],
  ['Pinterest', 'Flickr'],
  ['Zoom', 'Skype'],
  ['Dropbox', 'Google Drive'],
  ['PayPal', 'Venmo'],
  ['GitHub', 'GitLab'],
  ['WordPress', 'Squarespace'],
  ['Slack', 'Microsoft Teams'],
  ['WhatsApp', 'Telegram'],
  ['Airbnb', 'Booking.com'],
  ['Uber', 'Lyft'],
  // Emotions
  ['Happy', 'Cheerful'],
  ['Sad', 'Gloomy'],
  ['Angry', 'Furious'],
  ['Scared', 'Frightened'],
  ['Tired', 'Exhausted'],
  ['Excited', 'Thrilled'],
  ['Nervous', 'Anxious'],
  ['Calm', 'Peaceful'],
  
  // Weather
  ['Rainy', 'Drizzly'],
  ['Sunny', 'Bright'],
  ['Cloudy', 'Overcast'],
  ['Stormy', 'Tempestuous'],
  ['Windy', 'Breezy'],
  ['Foggy', 'Misty'],
  ['Humid', 'Muggy'],
  ['Chilly', 'Cold'],
  
  // Sports Equipment
  ['Racket', 'Paddle'],
  ['Cleats', 'Spikes'],
  ['Helmet', 'Headgear'],
  ['Bat', 'Club'],
  ['Goal', 'Net'],
  ['Jersey', 'Uniform'],
  
  // Musical Terms
  ['Melody', 'Tune'],
  ['Rhythm', 'Beat'],
  ['Symphony', 'Orchestra'],
  ['Song', 'Ballad'],
  ['Concert', 'Recital'],
  ['Band', 'Group'],
  
  // School Items
  ['Notebook', 'Journal'],
  ['Backpack', 'Rucksack'],
  ['Marker', 'Highlighter'],
  ['Ruler', 'Measuring Stick'],
  ['Calculator', 'Computer'],
  
  // Job Titles
  ['Teacher', 'Instructor'],
  ['Doctor', 'Physician'],
  ['Chef', 'Cook'],
  ['Writer', 'Author'],
  ['Artist', 'Painter'],
  ['Manager', 'Supervisor'],
  
  // Home Spaces
  ['Kitchen', 'Dining Room'],
  ['Bedroom', 'Chamber'],
  ['Bathroom', 'Restroom'],
  ['Garage', 'Carport'],
  ['Garden', 'Yard'],
  ['Basement', 'Cellar'],
  
  // Time Periods
  ['Morning', 'Dawn'],
  ['Evening', 'Dusk'],
  ['Night', 'Midnight'],
  ['Spring', 'Summer'],
  ['Autumn', 'Fall'],
  ['Past', 'History'],
  
  // Textures
  ['Smooth', 'Sleek'],
  ['Rough', 'Coarse'],
  ['Soft', 'Fluffy'],
  ['Hard', 'Solid'],
  ['Sticky', 'Gooey'],
  ['Slippery', 'Slick'],
  
  // Colors
  ['Crimson', 'Scarlet'],
  ['Azure', 'Cerulean'],
  ['Emerald', 'Jade'],
  ['Purple', 'Violet'],
  ['Golden', 'Yellow'],
  ['Silver', 'Gray'],
  
  
  // Space Related
  ['Galaxy', 'Universe'],
  ['Planet', 'Star'],
  ['Comet', 'Asteroid'],
  ['Meteor', 'Satellite'],
  ['Rocket', 'Shuttle'],
  
  // Medical Terms
  ['Vaccine', 'Medicine'],
  ['Surgery', 'Operation'],
  ['Symptom', 'Diagnosis'],
  ['Patient', 'Doctor'],
  ['Clinic', 'Hospital'],
  
  // Ocean Life
  ['Coral', 'Reef'],
  ['Octopus', 'Squid'],
  ['Seahorse', 'Starfish'],
  ['Jellyfish', 'Anemone'],
  ['Lobster', 'Crab'],
  
  // Art Supplies
  ['Canvas', 'Palette'],
  ['Brush', 'Easel'],
  ['Crayon', 'Pastel'],
  ['Sketch', 'Drawing'],
  ['Paint', 'Ink'],
  
  // Fantasy
  ['Dragon', 'Phoenix'],
  ['Wizard', 'Sorcerer'],
  ['Knight', 'Paladin'],
  ['Castle', 'Palace'],
  ['Magic', 'Spell'],
  
  // Science
  ['Atom', 'Molecule'],
  ['Theory', 'Hypothesis'],
  ['Element', 'Compound'],
  ['Energy', 'Force'],
  ['Matter', 'Mass'],
  
  // Architecture
  ['Bridge', 'Tunnel'],
  ['Tower', 'Skyscraper'],
  ['Temple', 'Cathedral'],
  ['Mansion', 'Villa'],
  ['Cottage', 'Cabin']
];